# Generated by Django 6.0.7 on 2026-08-03 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Informations complémentaires sur l'action"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(blank=True, help_text='Nom de la ressource concernée (Company, User, Document, Signature...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Identifiant de la ressource concernée', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource'], name='core_auditl_resourc_9fffc5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
    ]
